### ISSUE TITLE
Error plugin don't reconize my .h files

### ISSUE THREAD

**Issue by 0xskeksis** [bonsthie/nvim#3]
Hi, the error plugins don't recognize my .h files so he puts error everywere.
Do you know how to fix it ?
Thanks ^
![Screenshot from 2024-09-08 15-37-47](https://github.com/user-attachments/assets/4f257f54-967a-413f-a2a7-c3bdaf21bbfd)

**Comment by bonsthie** [comment]
Hi! The issue you're encountering is likely because my Neovim configuration uses the clangd language server, which is more advanced than the basic LSP in VSCode. However, unlike VSCode, clangd doesn't automatically generate an indexing file (like compile_commands.json). This is necessary for clangd to properly recognize your .h files and avoid the errors you're seeing.

To fix this, you'll need to generate a compile_commands.json file. You can use tools like [Bear](https://github.com/rizsotto/Bear) or [compiledb](https://github.com/nickdiego/compiledb) to do this.

Here’s a quick guide:

1. Bear:  Bear intercepts the build process and generates compile_commands.json automatically. You can install it with your package manager and then simply prepend your build command with bear. For example:
```bash
bear -- make
```
2. compiledb: Another option is compiledb, which parses build output and generates the required file. You can run it like this:
```bash
compiledb make
```
However, note that if the make process fails, Bear won’t generate the compile_commands.json file, since it depends on a successful build.

Once you've generated compile_commands.json, clangd should be able to index your project correctly.
